apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-pv
  namespace: rabbitmq
  labels:
    storage: main
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: rabbitmq
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      storage: main
