apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-pv
  namespace: {{ .Values.app.namespace }}
  labels:
    storage: {{ .Values.app.name }}
spec:
  storageClassName: {{ .Values.storage.name }}-storage
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: {{ .Values.storage.name }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
  selector:
    matchLabels:
      storage: {{ .Values.app.name }}