apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.port }}
      protocol: TCP
  selector:
    components: {{ .Values.app.name }}