apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.ports.admin }}
      protocol: TCP
      name: admin
    - port: {{ .Values.deployment.ports.main }}
      protocol: TCP
      name: main
  selector:
    components: rabbitmq