apiVersion: v1
kind: Pod
metadata:
  name: conv-app-pod
  labels:
    components: conv-app
spec:
  containers:
    - name: conv-app
      image: antonlarichev/conv-app:1.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
