apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.app.name }}
  template:
    metadata:
      name: {{ .Values.app.name }}
      labels:
        components: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.registry.mirror }}/antonlarichev/conv-app:{{ .Values.app.version }}"
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            limits: {{ .Values.deployment.limits | toYaml | nindent 14 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config